'use strict';

export default {
  CURRENT_APPEND: "CURRENT_APPEND",
  CURRENT_REPLACE: "CURRENT_REPLACE",
  SELECT: "SELECT",
  SET_ACTIVE_ICON: "SET_ACTIVE_ICON",
  LOAD_SETTINGS: "LOAD_SETTINGS",
  MODIFY_SETTINGS: "MODIFY_SETTINGS"
}
